iteration: 1f
import_path: I:\NorMITs Demand\import
assignment_model: NoHAM
base_year: 2018
future_years:
  - 2028
  - 2038
  - 2043
  - 2048
export_folder: E:\ntem_outputs
ntem_parameters:
  data_path: I:\Data\NTEM
  version: 8.0
  scenario: Core
matrix_import_path: I:\NorMITs Demand\import\noham\post_me\tms_seg_pa
hb_purposes_needed:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
nhb_purposes_needed:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 18
comparison_zone_systems:
  trip end: lad_2020
  matrix 1: lad_2020
time_periods:
  - 1
  - 2
  - 3
  - 4
user_classes:
  - commute
  - business
  - other
