iteration: 1.7
base_output_folder: I:\NorMITs Demand\Traveller Segmentation Tool
notem_iteration: 9.10
notem_export_home: I:\NorMITs Demand\NoTEM
scenario: SC01_JAM
matrix_folder: I:\NorMITs Demand\Distribution Model\iter9.10.3\train\Final Outputs\Full TP PA Matrices
model: NoRMS
matrix_zoning: NoRMS
year: 2018
disaggregation_output_segment: soc
trip_length_distribution_folder: I:\NorMITs Demand\import\traveller_segment_tool\trip_length_distributions\v1.1\uc_m_soc_m6
cost_folder: I:\NorMITs Demand\import\modal\train\costs\norms\userclass
aggregate_time_periods:
  - 1
  - 2
  - 3
  - 4
disaggregation_settings:
  export_original: yes
  export_furness: no
  maximum_furness_loops: 1999
  pa_furness_convergence: 0.1
  bandshare_convergence: 0.975
  max_bandshare_loops: 200
  multiprocessing_threads: -1
  pa_match_tolerance: 0.95
  minimum_bandshare_change: 1e-04
  trip_end_constraint: none
